### ISSUE TITLE
SQLite installed but have been deleted chatbot (RED-BOT)

### ISSUE THREAD

**Issue by FraCata00** [vongomben/fluid-networks#9]
So when I try to install sqlite from command-line with apposit command, node-red automatically delete me a node of chat-bot

**Comment by vongomben** [comment]
what if you try to install again chatbot? 
`npm install node-red-contrib-chatbot`

**Comment by FraCata00** [comment]
So I try to reinstall chat-bot form cmd now

**Comment by FraCata00** [comment]
So to resolve this problem I've been uninstall 2 node: ---> `npm uninstall node-red-contrib-chatbot`
and: ----> `npm uninstall node-red-node-sqlite`
After this so I've been updated node-red with: -----> `npm install -g --unsafe-perm node-red`
and after this I updated Node.js at the v16.0 (the latest version) from [https://nodejs.org/it/](url)
After this I rebooted my pc and I updated @mapbox/node-pre-gyp:
`npm uninstall node-pre-gyp --save`
and after
`npm install @mapbox/node-pre-gyp --save`
After this, I rebooted my pc, and reinstall chat-bot and sqlite in node-red but from cmd:
`npm install node-red-contrib-chatbot`
and
`npm install node-red-node-sqlite`

Now my node and npm version are:
Node version:        ---->  v16.0.0
NPM version:         ----> v7.11.1
Node-Red version: ----> v1.3.4
